
repos:
    - repo: https://github.com/psf/black
      rev: v22.3.0
      hooks:
        - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        - id: check-added-large-files
        - id: fix-encoding-pragma
        - id: double-quote-string-fixer
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          entry: poetry run pylint app/
          language: system
          always_run: true
          pass_filenames: false